export enum ErrorMessage {
  API_VALIDATION_ERROR = 'API_VALIDATION_ERROR',
  UNAUTHORIZED = 'UNAUTHORIZED',
  REQUEST_FORBIDDEN_ERROR = 'REQUEST_FORBIDDEN_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  UNPROCESSABLE = 'UNPROCESSABLE',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}

export enum ErrorCode {
  API_VALIDATION_ERROR = 400,
  UNAUTHORIZED = 401,
  REQUEST_FORBIDDEN_ERROR = 403,
  NOT_FOUND = 404,
  CONFLICT = 409,
  UNPROCESSABLE = 422,
  INTERNAL_SERVER_ERROR = 500,
}
